server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: notification-service
  rabbitmq:
    addresses: '${RABBITMQ_HOSTNAME:localhost}:5672'
rabbitmq:
  exchanges:
    core: core.exchange
  queues:
    core: core.queue
  routing-keys:
    core-notification: core.notification.routing-key
logging:
  level:
    org.springframework.web: WARN
    com.elm.sa.lgn.notificationservice: DEBUG
    com.elm.sa.lgn.amqp: DEBUG