eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.elm.sa.lgn.yakeenservice: DEBUG