server:
  port: 8085
spring:
  application:
    name: yakeen-service
yakeen:
  middleware:
    secret-token: "test-token"
    app-id: "test-token"
    app-key: "test-token"
    operator-id: "1000011021"
    client-ip-address: "10.0.0.0"
    lang: "ar"
    base-url: "https://yakeen-middleware.dev-apps.elm.sa"
    person-basic-info-url: "/api/v1/yakeen/mw/person/getPersonBasicInfo"
    vehicle-info-url: "/api/v1/yakeen/mw/vehicle/getVehicleInfo"
    vehicles-url: "/api/v1/yakeen/mw/vehicle/getListVehicles"
    vehicle-policy-info-url: "/api/v1/yakeen/mw/vehicle/getListVehiclePolicyInfo"