spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/coredb
    username: ${POSTGRES_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: postgres