eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8671}/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.elm.sa: DEBUG